name: Trigger accounting-folio-calculation-scheduler

on:
  schedule:
    - cron: '*/10 * * * *'
env:
  ENV: 'staging14'
  DATACENTER: '2'

jobs:
  echo:
    name: Trigger a scheduler each 10 minutes
    runs-on: ubuntu-latest
    steps:
      - name: Invoke POST /accounting-internal/folio
        run: curl -X POST -d {} "https://$ENV-$DATACENTER-internal.guesty.com/accounting-internal/folio"
