name: Trigger a job on a CRON Schedule

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  echo:
    name: Trigger a scheduler each 10 minutes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger folio-calculation-scheduler
        run: curl -X POST -d {} https://staging14-2-internal.guesty.com/accounting-internal/folio
